### ISSUE TITLE
Docker Swarm error: Service cannot be explicitly attached to the ingress network "ingress"

### ISSUE THREAD

**Issue by schiggi** [byjg/docker-easy-haproxy#36]
When using the default yml for Docker Swarm, I am getting the following error during start:

```python
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/services/9gffebl2qqovhlyf8nuit3kkb/update?version=9790
[...]
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/services/9gffebl2qqovhlyf8nuit3kkb/update?version=9790: Bad Request ("rpc error: code = InvalidArgument desc = Service cannot be explicitly attached to the ingress network "ingress"")
[...]
  File "/scripts/processor/__init__.py", line 176, in inspect_network
    service.update(networks = network_list)
  File "/scripts/processor/__init__.py", line 64, in refresh
    self.inspect_network()
    self.refresh()
  File "/scripts/processor/__init__.py", line 43, in __init__
  File "/scripts/main.py", line 7, in start
    processor_obj = ProcessorInterface.factory(os.getenv("EASYHAPROXY_DISCOVER"))
  File "/scripts/processor/__init__.py", line 52, in factory
    return Swarm()
  File "/scripts/processor/__init__.py", line 155, in __init__
    super().__init__()
```

My yml looks like this:
```yml
version: "3"

services:
  haproxy:
    image: byjg/easy-haproxy
    environment:
      EASYHAPROXY_DISCOVER: swarm
      EASYHAPROXY_SSL_MODE: "loose"
      HAPROXY_CUSTOMERRORS: "true"
      HAPROXY_USERNAME: admin
      HAPROXY_PASSWORD: password
      HAPROXY_STATS_PORT: 1936
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "1936:1936/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    networks:
      - proxy_public
networks:
  proxy_public:
    external: true
```

**Comment by schiggi** [comment]
Thanks for getting backt to me! But the network is created correctly with the overlay option.
![image](https://user-images.githubusercontent.com/3776606/221408615-2c807b91-5ea5-41df-8239-fffa25ed7642.png)

Moreover, the error message indicates that the problem is not the created network but the default `ingress` network.
`Bad Request ("rpc error: code = InvalidArgument desc = Service cannot be explicitly attached to the ingress network "ingress"")`

Not sure how to debug from here.

**Comment by schiggi** [comment]
Thanks for the advice. Tried it without a network and same error popped up.
In my understanding, every [service that publishes ports gets automatically the ingress network attached](https://github.com/moby/moby/issues/33878#issuecomment-312524929). So somehow the script tries to reattach the default ingress network.

I tried a different approach and stopped other stacks before starting easyhaproxy. These stacks had no labels. And it worked. haproxy came up properly*. After some more testing, it seems that I need to start haproxy first before other stacks (but services seem to be fine). And if I want to update haproxy settings, I need to stop other stacks, restart haproxy stack and then start the other ones.

Another problems seems to be that I am getting the same error about ingress network, when trying to add some haproxy labels to stacks. Needless to say that proxing doesn't work.

Any ideas where to investigate further?


*Its default network attached itself to another docker service running (Portainer Agent). Not sure if that is good or bad.

**Comment by schiggi** [comment]
Great, thanks, tried it. It seems that it is starting now. However, in my configuration below it seems to have removed the _odoo-test_ network from services. 

Only `ingress` and `lb_default` (_lb_ being the stack name for haproxy) are attached to `web` service container.
```yml
version: '3.3'
services:
  db:
    image: postgres:13
    command:
     - postgres
     - -c
     - max_connections=200
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: test
      POSTGRES_PASSWORD_FILE: /run/secrets/odoo_erp_test_db_password
    ports:
     - 5432
    networks:
     - odoo-test
    volumes:
     - odoo-test-db-data:/var/lib/postgresql/data/pgdata
    secrets:
     - odoo_erp_test_db_password
  web:
    image: odoo/odoo:v14
    deploy:
      replicas: 1
      labels:
        easyhaproxy.frontend.host: test.domain.de
        easyhaproxy.frontend.port: 443
        easyhaproxy.frontend.sslcert: /run/secrets/erp-test-cloudflare-certs-base64
        easyhaproxy.frontend.ssl: "true"
        easyhaproxy.frontend.localport: 8069
    command:
     - --max-cron-threads=1
    environment:
      PASSWORD_FILE: /run/secrets/odoo_erp_test_db_password
      USER: odoo
    ports:
     - 8069
     - 8071
     - 8072
    volumes:
     - odoo-test-web-data:/var/lib/odoo
    networks:
     - odoo-test
    secrets:
     - odoo_erp_test_db_password
     - erp-test-cloudflare-certs-base64
networks:
  odoo-test:
    driver: overlay
volumes:
    odoo-test-db-data:
    odoo-test-web-data:
secrets:
  odoo_erp_test_db_password:
    external: true
  erp-test-cloudflare-certs-base64:
    external: true
```
